// Generated by the Turbulenz Engine: https://github.com/turbulenz/turbulenz_engine
// Turbulenz Engine distributed under the MIT license: https://github.com/turbulenz/turbulenz_engine/blob/master/LICENSE

//
//  Config DEBUG
//
/*exported Config*/

var Config =
{
    // Debug
    enableDynamicUI : true, // Enable the debug UI
    // Audio
    disableSound : false // Turn off sound for the build
};
